import Head from 'next/head'
import { Footer, Navbar, Portfolio, Profile } from '@/components'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState<boolean>(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Karun Krishnan | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='p-10 pb-0 dark:bg-teal-900'>
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
        <Profile />
        <hr className='my-20 mx-80 border-teal-900 dark:border-slate-100' />
        <Portfolio />
        <Footer />
      </main>
    </div>
  )
}
